var GAME_LEVELS = [
  ["                                                                                ",
   "                   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxx",
   "                                                         o                      ",
   "                                                         o                      ",
   "                                                         o                      ",
   "           xxx                                                                  ",
   "                                                        xxx       xxx           ",
   "                 yyy       xx  xx                                xx!xx          ",
   "                                         o o      xx             x!!!x          ",
   "                                                                 xx!xx          ",
   "                      xxx               xxxxx        xx     o     xvx           ",
   "                                                                            xx  ",
   "  xx                        o o    x x                     xxx               x  ",
   "  x                                                                          x  ",
   "  x        o          o    xxxxx                       yyy                 o x  ",
   "  x                                                                          x  ",
   "  x  @    ppp                            ppp                        xxxxx    x  ",
   "  xxxxxxxxxxxxyyyxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxx  ",
   "             x   x                                   x     x                    ",
   "             x!!!x                                   x!!!!!x                    ",
   "             x!!!x                                   x!!!!!x                    ",
   "             xxxxx                                   xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                                                  ",
   "                                                                                                                  ",
   "                                                       xxx     xxx     xxx                       xxx              ",
   "                                                      xx!xx   xx!xx   xx!xx                     xx!xx             ",
   "                                                      x!!!x   x!!!x   x!!!x                     x!!!x             ",
   "                                                      xx!xx   xx!xx   xx!xx                     xx!xx             ",
   "               oooooo                                  xvx     xvx     xvx                       xvx              ",
   "     @       xxxxxxxxxx                                                                                           ",
   "    xxx      x        xx                                                                                          ",
   "    x x      x        xx                                                             o                            ",
   "    x x      x        xx                                                                                          ",
   "    x x      x        xx                                 o         o        o                                     ",
   "    x x      x        xx                           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                ",
   "    x x      x        xx                 oo                                                                       ",
   "    x x      x        xx               xxxxx                                                                      ",
   "    x x      x        xx                                                                                          ",
   "    x x      x        xx                                                                                          ",
   "    x x      x        xx                                                                                          ",
   "    x x      x        xx          o             xxxx                                                              ",
   "    x x      x        xx          o                                                                               ",
   "    x x      x        xx                 xxx                                                                      ",
   "    x x      x         x        o   o                                                                             ",
   "    x x      x         x       xxxxxxx                                                                          xx",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                                           o             x",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                             o  x",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                                x",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                        o  o             o   o  x",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                   xxxxxxxxxxxxxx    xxxxxxxxxxxx",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!1"],
  ["                                                                                                              ",
   "                                                                                                              ", 
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "  xxx                                                                                                         ",
   "  x x                                                                                                         ",
   "  x                                                                                                       xx  ",
   "  x                                                                                                        x  ",
   "  x                                                                                                        x  ",
   "  x                                                                                       o                x  ",
   "  x                                                                                 o                      x  ",
   "  x                                 o                                              xxx             o       x  ",
   "  x                                                                                                        x  ",
   "  x  @                =                              =   ooo                        =                      x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!1"],
   ["                                                                                                             ",
   "                                                                                                              ", 
   "                                    x              x                    x            x                        ",
   "                                     x            x                     x            x            x           ",
   "                                      x          x                      x            x            x           ",                                                                                                                  
   "                                       x       x                        x            x            x           ",
   "                                        x     x                         x            x x          x           ",
   "                                         x  x                           x            x x x        x           ",                                                                                                                  
   "                                           x    xxxxxxxxxx x      x     x            x   xxxxx    x           ",
   "                                           x    x        x x      x     x            x x x    x   x           ",
   "                                           x    x        x x      x     x     xx     x x x     x  x           ",                                                                                                                  
   "                                           x    x        x x      x     x    x x    x  x x     x              ",
   "                                           x    x        x x      x      x  x   x  x   x x     x  x           ",
   "                                           x    x        x x      x       x      x     x x     x  x           ",
   "  xxx                                      x    xxxxxxxxxx  xxxxxx                                            ",
   "  x x                                                                                                         ",
   "  x                                                                                                       xx  ",
   "  x                                                                                                        x  ",
   "  x                                                                                                        x  ",
   "  x                                                                                                        x  ",
   "  x                                                                                                        x  ",
   "  x                                                                                                        x  ",
   "  x                                                                                                        x  ",
   "  x  @                                                                                                   o x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!1"],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
